-- MySQL Script generated by MySQL Workbench
-- Tue Dec  8 20:41:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_FC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_FC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_FC` DEFAULT CHARACTER SET utf8 ;
USE `projeto_FC` ;

-- -----------------------------------------------------
-- Table `projeto_FC`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_FC`.`empresa` (
  `id_pro` BIGINT NOT NULL AUTO_INCREMENT,
  `valor_mp` DECIMAL(10,5) NOT NULL,
  `capital` DECIMAL(10,5) NOT NULL,
  PRIMARY KEY (`id_pro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_FC`.`simulacao_lucro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_FC`.`simulacao_lucro` (
  `id_simul` INT NOT NULL AUTO_INCREMENT,
  `simulacao_valor` DECIMAL(10,5) NOT NULL,
  `estoque_nece` INT NOT NULL,
  `margem_lucro` DECIMAL(10,5) NOT NULL,
  PRIMARY KEY (`id_simul`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_FC`.`Lucro_real`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_FC`.`Lucro_real` (
  `id_lucro` INT NOT NULL AUTO_INCREMENT,
  `mês` VARCHAR(45) NOT NULL,
  `valor_produto` DECIMAL(10,5) NOT NULL,
  `demanda` INT NOT NULL,
  PRIMARY KEY (`id_lucro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_FC`.`custo_fixo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_FC`.`custo_fixo` (
  `id_custo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,5) NOT NULL,
  PRIMARY KEY (`id_custo`, `nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_FC`.`inicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_FC`.`inicio` (
  `id_inicio` INT NOT NULL AUTO_INCREMENT,
  `cap_pro` INT NOT NULL,
  `custo_med` FLOAT NOT NULL,
  PRIMARY KEY (`id_inicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_FC`.`valores_ideais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_FC`.`valores_ideais` (
  `id_val` BIGINT NOT NULL AUTO_INCREMENT,
  `preco` DECIMAL(10,5) NOT NULL,
  `estoque_nec` INT NOT NULL,
  `raiz_um` DECIMAL(10,5) NOT NULL,
  `raiz_dois` DECIMAL(10,5) NOT NULL,
  `lucro_ideal` DECIMAL(10,5) NOT NULL,
  PRIMARY KEY (`id_val`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
